# Runs all tests
name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev/develop
      - main
  pull_request:
    branches:
      - dev/develop
      - main

    
    
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.1'
      
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build clang
          
      - name: Install dependencies
        run: sudo apt-get install -y python3-venv
          
      - name: Build
        run: |
          mkdir build-Release
          cd build-Release
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DBUILD_TESTS=ON ..
          cmake --build .
          
      - name: Run tests
        run: |
          cd build-Release
          ctest
